// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace POBeckEnd.Models
{
    public partial class DbPOContext : DbContext
    {
        public DbPOContext()
        {
        }

        public DbPOContext(DbContextOptions<DbPOContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TblPoCustomer> TblPoCustomer { get; set; }
        public virtual DbSet<TblPoDetail> TblPoDetail { get; set; }
        public virtual DbSet<TblPoHeader> TblPoHeader { get; set; }
        public virtual DbSet<TblPoShipment> TblPoShipment { get; set; }
        public virtual DbSet<TblPoVendor> TblPoVendor { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TblPoCustomer>(entity =>
            {
                entity.ToTable("tbl_po_customer");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Alamat)
                    .HasMaxLength(200)
                    .IsUnicode(false)
                    .HasColumnName("alamat");

                entity.Property(e => e.ContactPerson)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("contact_person");

                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("created_by");

                entity.Property(e => e.CreatedDate)
                    .HasColumnType("datetime")
                    .HasColumnName("created_date");

                entity.Property(e => e.Email)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("email");

                entity.Property(e => e.IsDeleted).HasColumnName("is_deleted");

                entity.Property(e => e.Nama)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("nama");

                entity.Property(e => e.NoTelp)
                    .HasMaxLength(15)
                    .IsUnicode(false)
                    .HasColumnName("no_telp");

                entity.Property(e => e.PoHeaderId).HasColumnName("po_header_id");

                entity.Property(e => e.UpdatedBy)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("updated_by");

                entity.Property(e => e.UpdatedDate)
                    .HasColumnType("datetime")
                    .HasColumnName("updated_date");
            });

            modelBuilder.Entity<TblPoDetail>(entity =>
            {
                entity.ToTable("tbl_po_detail");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("created_by");

                entity.Property(e => e.CreatedDate)
                    .HasColumnType("datetime")
                    .HasColumnName("created_date");

                entity.Property(e => e.HargaUnit)
                    .HasColumnType("numeric(18, 0)")
                    .HasColumnName("harga_unit");

                entity.Property(e => e.IsDeleted).HasColumnName("is_deleted");

                entity.Property(e => e.Keterangan)
                    .HasMaxLength(200)
                    .IsUnicode(false)
                    .HasColumnName("keterangan");

                entity.Property(e => e.No).HasColumnName("no");

                entity.Property(e => e.PoHeaderId).HasColumnName("po_header_id");

                entity.Property(e => e.Qty).HasColumnName("qty");

                entity.Property(e => e.Total)
                    .HasColumnType("numeric(18, 0)")
                    .HasColumnName("total");

                entity.Property(e => e.Unit)
                    .HasMaxLength(15)
                    .IsUnicode(false)
                    .HasColumnName("unit");

                entity.Property(e => e.UpdatedBy)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("updated_by");

                entity.Property(e => e.UpdatedDate)
                    .HasColumnType("datetime")
                    .HasColumnName("updated_date");

                entity.HasOne(d => d.PoHeader)
                    .WithMany(p => p.TblPoDetail)
                    .HasForeignKey(d => d.PoHeaderId)
                    .HasConstraintName("fk_po_header_id");
            });

            modelBuilder.Entity<TblPoHeader>(entity =>
            {
                entity.ToTable("tbl_po_header");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.AlamatPerusahaan)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("alamat_perusahaan");

                entity.Property(e => e.CatatanTambahan)
                    .HasMaxLength(200)
                    .IsUnicode(false)
                    .HasColumnName("catatan_tambahan");

                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("created_by");

                entity.Property(e => e.CreatedDate)
                    .HasColumnType("datetime")
                    .HasColumnName("created_date");

                entity.Property(e => e.Diskon)
                    .HasColumnType("numeric(18, 0)")
                    .HasColumnName("diskon");

                entity.Property(e => e.Email)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("email");

                entity.Property(e => e.IsDeleted).HasColumnName("is_deleted");

                entity.Property(e => e.Jabatan)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("jabatan");

                entity.Property(e => e.Nama)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("nama");

                entity.Property(e => e.NoPo)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("no_po");

                entity.Property(e => e.NoTelp)
                    .HasMaxLength(15)
                    .IsUnicode(false)
                    .HasColumnName("no_telp");

                entity.Property(e => e.PerusahaanTujuan)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("perusahaan_tujuan");

                entity.Property(e => e.Ppn)
                    .HasColumnType("numeric(18, 0)")
                    .HasColumnName("ppn");

                entity.Property(e => e.Subtotal)
                    .HasColumnType("numeric(18, 0)")
                    .HasColumnName("subtotal");

                entity.Property(e => e.Tanggal)
                    .HasColumnType("datetime")
                    .HasColumnName("tanggal");

                entity.Property(e => e.Total)
                    .HasColumnType("numeric(18, 0)")
                    .HasColumnName("total");

                entity.Property(e => e.UpdatedBy)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("updated_by");

                entity.Property(e => e.UpdatedDate)
                    .HasColumnType("datetime")
                    .HasColumnName("updated_date");

                entity.Property(e => e.Website)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("website");
            });

            modelBuilder.Entity<TblPoShipment>(entity =>
            {
                entity.ToTable("tbl_po_shipment");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("created_by");

                entity.Property(e => e.CreatedDate)
                    .HasColumnType("datetime")
                    .HasColumnName("created_date");

                entity.Property(e => e.IsDeleted).HasColumnName("is_deleted");

                entity.Property(e => e.PoHeaderId).HasColumnName("po_header_id");

                entity.Property(e => e.ShipTerms)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("ship_terms");

                entity.Property(e => e.ShipVia)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ship_via");

                entity.Property(e => e.UpdatedBy)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("updated_by");

                entity.Property(e => e.UpdatedDate)
                    .HasColumnType("datetime")
                    .HasColumnName("updated_date");
            });

            modelBuilder.Entity<TblPoVendor>(entity =>
            {
                entity.ToTable("tbl_po_vendor");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Alamat)
                    .HasMaxLength(200)
                    .IsUnicode(false)
                    .HasColumnName("alamat");

                entity.Property(e => e.ContactPerson)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("contact_person");

                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("created_by");

                entity.Property(e => e.CreatedDate)
                    .HasColumnType("datetime")
                    .HasColumnName("created_date");

                entity.Property(e => e.Email)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("email");

                entity.Property(e => e.IsDeleted).HasColumnName("is_deleted");

                entity.Property(e => e.Nama)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("nama");

                entity.Property(e => e.NoTelp)
                    .HasMaxLength(15)
                    .IsUnicode(false)
                    .HasColumnName("no_telp");

                entity.Property(e => e.PoHeaderId).HasColumnName("po_header_id");

                entity.Property(e => e.UpdatedBy)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("updated_by");

                entity.Property(e => e.UpdatedDate)
                    .HasColumnType("datetime")
                    .HasColumnName("updated_date");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}