// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace POBeckEnd.Models
{
    public partial class TblPoDetail
    {
        public long Id { get; set; }
        public long? PoHeaderId { get; set; }
        public int? No { get; set; }
        public string Keterangan { get; set; }
        public string Unit { get; set; }
        public int? Qty { get; set; }
        public decimal? HargaUnit { get; set; }
        public decimal? Total { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public bool? IsDeleted { get; set; }

        public virtual TblPoHeader PoHeader { get; set; }
    }
}