// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace POBeckEnd.Models
{
    public partial class TblPoShipment
    {
        public long Id { get; set; }
        public long? PoHeaderId { get; set; }
        public string ShipVia { get; set; }
        public string ShipTerms { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public bool? IsDeleted { get; set; }
    }
}